AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is the AWS Lambda functions
Parameters:
  Environment:
    Type: String
    Description: This key is used for environment
    Default: dev
  UniqueName:
    Type: String
    Description: This is for the new file
    Default: hari
Mappings:
  EnvironmentMap:
    dev:
      tableName: megha_customers
Resources:
  customerDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
      TableName:
        Fn::Sub: ${UniqueName}-${Environment}-customers
  createCustomerLambdaFunction:
    Type: AWS::Serverless::Function
    DependsOn: customerDynamoDBTable
    Properties:
      Handler: index.handler
      CodeUri: s3://hari-mwdet-repo/getaccount/0a76035daba21dce7eed1eb5bf2d6a57
      FunctionName:
        Fn::Sub: ${UniqueName}-${Environment}-create-customer
      Description: create customer data
      Runtime: nodejs14.x
      MemorySize: 128
      Timeout: 300
      Environment:
        Variables:
          TABLE_NAME:
            Ref: customerDynamoDBTable
      Policies:
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:*
          Resource:
          - Fn::GetAtt:
            - customerDynamoDBTable
            - Arn
  createCustomerLambdaPermissionForAPI:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: createCustomerLambdaFunction
      Principal: apigateway.amazonaws.com
