
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Invoke State Machine Lambda

Parameters:
  UniqueName:
    Description: A unique prefix given to all of the AWS resources
    Type: String
    Default: hari

Resources:
  RidesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${UniqueName}-http-crud-tutorial-items
      PrimaryKey:
        Name: id
        Type: String

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${UniqueName}-http-crud-tutorial-function
      Handler: index.handler
      Runtime: nodejs14.x
      CodeUri: ./lambdas/getaccount/src
      MemorySize: 256
      Timeout: 120
      Policies:
        - AWSLambdaExecute
        - AWSStepFunctionsFullAccess
      Events:
          WildRydes1:
            Type: Api 
            Properties:
              Path: /items
              Method: get
          WildRydes2:
            Type: Api 
            Properties:
              Path: /items
              Method: put